---
- name: install apache et curl
  apt:
     name: "{{item.name}}"
     state: present
  loop:
     - name: apache2
     - name: curl
  when: 
     - ansible_facts['distribution'] == 'Ubuntu'
     - ansible_facts['distribution_version'] ==  '18.04'

- name: copy template html
  template:
    src: './templates/index.html.j2'
    dest: '/var/www/html/index.html'


- name: start apache2 
  #command: service apache2 start
  service:
     name: apache2
     state: started
  register: resume

- name: ok start
  debug:
     msg: "{{resume}}"

- name: check website 200
  uri:
    url: "http://host_web"
    status_code: 200
  delegate_to: localhost
